/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { RockMaterial } from "./materials/rock";

/*
export function Garage() {
  const gltf = useGLTF("/models/tony-stark-garage.glb");
  return (
    // <Suspense fallback={null}>
      <primitive object={gltf.scene} />
    // </Suspense>
  );
}
*/

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
    mesh_0_1: THREE.Mesh;
    mesh_0_2: THREE.Mesh;
    mesh_0_3: THREE.Mesh;
    mesh_0_4: THREE.Mesh;
    mesh_0_5: THREE.Mesh;
    mesh_0_6: THREE.Mesh;
    mesh_0_7: THREE.Mesh;
    mesh_0_8: THREE.Mesh;
    mesh_0_9: THREE.Mesh;
    mesh_0_10: THREE.Mesh;
    mesh_0_11: THREE.Mesh;
    mesh_0_12: THREE.Mesh;
    mesh_0_13: THREE.Mesh;
    mesh_0_14: THREE.Mesh;
    mesh_0_15: THREE.Mesh;
    mesh_0_16: THREE.Mesh;
    mesh_0_17: THREE.Mesh;
    mesh_0_18: THREE.Mesh;
    mesh_0_19: THREE.Mesh;
    mesh_0_20: THREE.Mesh;
    mesh_0_21: THREE.Mesh;
    mesh_0_22: THREE.Mesh;
    mesh_0_23: THREE.Mesh;
    mesh_0_24: THREE.Mesh;
    mesh_0_25: THREE.Mesh;
    mesh_0_26: THREE.Mesh;
    mesh_0_27: THREE.Mesh;
    mesh_0_28: THREE.Mesh;
    mesh_0_29: THREE.Mesh;
    mesh_0_30: THREE.Mesh;
    mesh_0_31: THREE.Mesh;
    mesh_0_32: THREE.Mesh;
    mesh_0_33: THREE.Mesh;
    mesh_0_34: THREE.Mesh;
    mesh_0_35: THREE.Mesh;
    mesh_0_36: THREE.Mesh;
    mesh_0_37: THREE.Mesh;
    mesh_0_38: THREE.Mesh;
    mesh_0_39: THREE.Mesh;
    mesh_0_40: THREE.Mesh;
    mesh_0_41: THREE.Mesh;
    mesh_0_42: THREE.Mesh;
    mesh_0_43: THREE.Mesh;
    mesh_0_44: THREE.Mesh;
    mesh_0_45: THREE.Mesh;
    mesh_0_46: THREE.Mesh;
    mesh_0_47: THREE.Mesh;
    mesh_0_48: THREE.Mesh;
    mesh_0_49: THREE.Mesh;
    mesh_0_50: THREE.Mesh;
    mesh_0_51: THREE.Mesh;
    mesh_0_52: THREE.Mesh;
    mesh_0_53: THREE.Mesh;
    mesh_0_54: THREE.Mesh;
    mesh_0_55: THREE.Mesh;
    mesh_0_56: THREE.Mesh;
    mesh_0_57: THREE.Mesh;
    mesh_0_58: THREE.Mesh;
    mesh_0_59: THREE.Mesh;
    mesh_0_60: THREE.Mesh;
    mesh_0_61: THREE.Mesh;
    mesh_0_62: THREE.Mesh;
    mesh_0_63: THREE.Mesh;
    mesh_0_64: THREE.Mesh;
    mesh_0_65: THREE.Mesh;
    mesh_0_66: THREE.Mesh;
    mesh_0_67: THREE.Mesh;
    mesh_0_68: THREE.Mesh;
    mesh_0_69: THREE.Mesh;
    mesh_0_70: THREE.Mesh;
    mesh_0_71: THREE.Mesh;
    mesh_0_72: THREE.Mesh;
    mesh_0_73: THREE.Mesh;
    mesh_0_74: THREE.Mesh;
    mesh_0_75: THREE.Mesh;
    mesh_0_76: THREE.Mesh;
    mesh_0_77: THREE.Mesh;
    mesh_0_78: THREE.Mesh;
    mesh_0_79: THREE.Mesh;
    mesh_0_80: THREE.Mesh;
    mesh_0_81: THREE.Mesh;
    mesh_0_82: THREE.Mesh;
    mesh_0_83: THREE.Mesh;
    mesh_0_84: THREE.Mesh;
    mesh_0_85: THREE.Mesh;
    mesh_0_86: THREE.Mesh;
    mesh_0_87: THREE.Mesh;
    mesh_0_88: THREE.Mesh;
    mesh_0_89: THREE.Mesh;
    mesh_0_90: THREE.Mesh;
    mesh_0_91: THREE.Mesh;
    mesh_0_92: THREE.Mesh;
    mesh_0_93: THREE.Mesh;
    mesh_0_94: THREE.Mesh;
    mesh_0_95: THREE.Mesh;
    mesh_0_96: THREE.Mesh;
    mesh_0_97: THREE.Mesh;
    mesh_0_98: THREE.Mesh;
    mesh_0_99: THREE.Mesh;
    mesh_0_100: THREE.Mesh;
    mesh_0_101: THREE.Mesh;
    mesh_0_102: THREE.Mesh;
    mesh_0_103: THREE.Mesh;
    mesh_0_104: THREE.Mesh;
    mesh_0_105: THREE.Mesh;
    mesh_0_106: THREE.Mesh;
    mesh_0_107: THREE.Mesh;
    mesh_0_108: THREE.Mesh;
    mesh_0_109: THREE.Mesh;
    mesh_0_110: THREE.Mesh;
    mesh_0_111: THREE.Mesh;
    mesh_0_112: THREE.Mesh;
    mesh_0_113: THREE.Mesh;
    mesh_0_114: THREE.Mesh;
    mesh_0_115: THREE.Mesh;
    mesh_0_116: THREE.Mesh;
    mesh_0_117: THREE.Mesh;
    mesh_0_118: THREE.Mesh;
    mesh_0_119: THREE.Mesh;
    mesh_0_120: THREE.Mesh;
    mesh_0_121: THREE.Mesh;
    mesh_0_122: THREE.Mesh;
    mesh_0_123: THREE.Mesh;
    mesh_0_124: THREE.Mesh;
    mesh_0_125: THREE.Mesh;
    mesh_0_126: THREE.Mesh;
    mesh_0_127: THREE.Mesh;
    mesh_0_128: THREE.Mesh;
    mesh_0_129: THREE.Mesh;
    mesh_0_130: THREE.Mesh;
    mesh_0_131: THREE.Mesh;
    mesh_0_132: THREE.Mesh;
    mesh_0_133: THREE.Mesh;
    mesh_0_134: THREE.Mesh;
    mesh_0_135: THREE.Mesh;
    mesh_0_136: THREE.Mesh;
    mesh_0_137: THREE.Mesh;
    mesh_0_138: THREE.Mesh;
    mesh_0_139: THREE.Mesh;
    mesh_0_140: THREE.Mesh;
    mesh_0_141: THREE.Mesh;
    mesh_0_142: THREE.Mesh;
    mesh_0_143: THREE.Mesh;
    mesh_0_144: THREE.Mesh;
    mesh_0_145: THREE.Mesh;
    mesh_0_146: THREE.Mesh;
    mesh_0_147: THREE.Mesh;
    mesh_0_148: THREE.Mesh;
    mesh_0_149: THREE.Mesh;
    mesh_0_150: THREE.Mesh;
    mesh_0_151: THREE.Mesh;
    mesh_0_152: THREE.Mesh;
    mesh_0_153: THREE.Mesh;
    mesh_0_154: THREE.Mesh;
    mesh_0_155: THREE.Mesh;
    mesh_0_156: THREE.Mesh;
    mesh_0_157: THREE.Mesh;
    mesh_0_158: THREE.Mesh;
    mesh_0_159: THREE.Mesh;
    mesh_0_160: THREE.Mesh;
    mesh_0_161: THREE.Mesh;
    mesh_0_162: THREE.Mesh;
    mesh_0_163: THREE.Mesh;
    mesh_0_164: THREE.Mesh;
    mesh_0_165: THREE.Mesh;
    mesh_0_166: THREE.Mesh;
    mesh_0_167: THREE.Mesh;
    mesh_0_168: THREE.Mesh;
    mesh_0_169: THREE.Mesh;
    mesh_0_170: THREE.Mesh;
    mesh_0_171: THREE.Mesh;
    mesh_0_172: THREE.Mesh;
    mesh_0_173: THREE.Mesh;
    mesh_0_174: THREE.Mesh;
    mesh_0_175: THREE.Mesh;
    mesh_0_176: THREE.Mesh;
    mesh_0_177: THREE.Mesh;
    mesh_0_178: THREE.Mesh;
    mesh_0_179: THREE.Mesh;
    mesh_0_180: THREE.Mesh;
    mesh_0_181: THREE.Mesh;
    mesh_0_182: THREE.Mesh;
    mesh_0_183: THREE.Mesh;
    mesh_0_184: THREE.Mesh;
    mesh_0_185: THREE.Mesh;
    mesh_0_186: THREE.Mesh;
    mesh_0_187: THREE.Mesh;
    mesh_0_188: THREE.Mesh;
    mesh_0_189: THREE.Mesh;
    mesh_0_190: THREE.Mesh;
    mesh_0_191: THREE.Mesh;
    mesh_0_192: THREE.Mesh;
    mesh_0_193: THREE.Mesh;
    mesh_0_194: THREE.Mesh;
    mesh_0_195: THREE.Mesh;
    mesh_0_196: THREE.Mesh;
    mesh_0_197: THREE.Mesh;
    mesh_0_198: THREE.Mesh;
    mesh_0_199: THREE.Mesh;
    mesh_0_200: THREE.Mesh;
    mesh_0_201: THREE.Mesh;
    mesh_0_202: THREE.Mesh;
    mesh_0_203: THREE.Mesh;
    mesh_0_204: THREE.Mesh;
    mesh_0_205: THREE.Mesh;
    mesh_0_206: THREE.Mesh;
    mesh_0_207: THREE.Mesh;
    mesh_0_208: THREE.Mesh;
    mesh_0_209: THREE.Mesh;
    mesh_0_210: THREE.Mesh;
    mesh_0_211: THREE.Mesh;
    mesh_0_212: THREE.Mesh;
    mesh_0_213: THREE.Mesh;
    mesh_0_214: THREE.Mesh;
    mesh_0_215: THREE.Mesh;
    mesh_0_216: THREE.Mesh;
    mesh_0_217: THREE.Mesh;
    mesh_0_218: THREE.Mesh;
    mesh_0_219: THREE.Mesh;
    mesh_0_220: THREE.Mesh;
    mesh_0_221: THREE.Mesh;
    mesh_0_222: THREE.Mesh;
    mesh_0_223: THREE.Mesh;
    mesh_0_224: THREE.Mesh;
    mesh_0_225: THREE.Mesh;
    mesh_0_226: THREE.Mesh;
    mesh_0_227: THREE.Mesh;
    mesh_0_228: THREE.Mesh;
    mesh_0_229: THREE.Mesh;
    mesh_14: THREE.Mesh;
    mesh_14_1: THREE.Mesh;
    group_2_3: THREE.Mesh;
    group_3_3: THREE.Mesh;
    group_4_3: THREE.Mesh;
    mesh_18: THREE.Mesh;
    mesh_18_1: THREE.Mesh;
    group_2_4: THREE.Mesh;
    group_3_4: THREE.Mesh;
    group_4_4: THREE.Mesh;
    mesh_22: THREE.Mesh;
    mesh_22_1: THREE.Mesh;
    group_2_5: THREE.Mesh;
    group_3_5: THREE.Mesh;
    group_4_5: THREE.Mesh;
    mesh_26: THREE.Mesh;
    mesh_26_1: THREE.Mesh;
    group_2_6: THREE.Mesh;
    group_3_6: THREE.Mesh;
    group_4_6: THREE.Mesh;
    mesh_39: THREE.Mesh;
    mesh_39_1: THREE.Mesh;
    group_2_10: THREE.Mesh;
    group_3_10: THREE.Mesh;
    group_4_10: THREE.Mesh;
    mesh_43: THREE.Mesh;
    mesh_43_1: THREE.Mesh;
    group_2_11: THREE.Mesh;
    group_3_11: THREE.Mesh;
    group_4_11: THREE.Mesh;
    mesh_47: THREE.Mesh;
    mesh_47_1: THREE.Mesh;
    group_2_12: THREE.Mesh;
    group_3_12: THREE.Mesh;
    group_4_12: THREE.Mesh;
    mesh_51: THREE.Mesh;
    mesh_51_1: THREE.Mesh;
    group_2_13: THREE.Mesh;
    group_3_13: THREE.Mesh;
    group_4_13: THREE.Mesh;
    mesh_30: THREE.Mesh;
    mesh_30_1: THREE.Mesh;
    group_2_7: THREE.Mesh;
    group_3_7: THREE.Mesh;
    group_4_7: THREE.Mesh;
    Component_6_1: THREE.Mesh;
    mesh_35: THREE.Mesh;
    mesh_35_1: THREE.Mesh;
    group_2_8: THREE.Mesh;
    group_3_8: THREE.Mesh;
    group_4_8: THREE.Mesh;
    mesh_55: THREE.Mesh;
    mesh_55_1: THREE.Mesh;
    group_2_9: THREE.Mesh;
    group_3_9: THREE.Mesh;
    group_4_9: THREE.Mesh;
    mesh_1: THREE.Mesh;
    mesh_1_1: THREE.Mesh;
    group_2: THREE.Mesh;
    group_3: THREE.Mesh;
    group_4: THREE.Mesh;
    Component_6: THREE.Mesh;
    mesh_6: THREE.Mesh;
    mesh_6_1: THREE.Mesh;
    group_2_1: THREE.Mesh;
    group_3_1: THREE.Mesh;
    group_4_1: THREE.Mesh;
    mesh_10: THREE.Mesh;
    mesh_10_1: THREE.Mesh;
    group_2_2: THREE.Mesh;
    group_3_2: THREE.Mesh;
    group_4_2: THREE.Mesh;
  };
  materials: {};
};

const shouldCastShadow = false;
const shouldReceiveShadow = false;

export function Garage(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/models/tony-stark-garage.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_1.geometry}
        material={nodes.mesh_0_1.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_2.geometry}
        material={nodes.mesh_0_2.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_3.geometry}
        material={nodes.mesh_0_3.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_4.geometry}
        material={nodes.mesh_0_4.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_5.geometry}
        material={nodes.mesh_0_5.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_6.geometry}
        material={nodes.mesh_0_6.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_7.geometry}
        material={nodes.mesh_0_7.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_8.geometry}
        material={nodes.mesh_0_8.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_9.geometry}
        material={nodes.mesh_0_9.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_10.geometry}
        material={nodes.mesh_0_10.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_11.geometry}
        material={nodes.mesh_0_11.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_12.geometry}
        material={nodes.mesh_0_12.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_13.geometry}
        material={nodes.mesh_0_13.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_14.geometry}
        material={nodes.mesh_0_14.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_15.geometry}
        material={nodes.mesh_0_15.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_16.geometry}
        material={nodes.mesh_0_16.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_17.geometry}
        material={nodes.mesh_0_17.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_18.geometry}
        material={nodes.mesh_0_18.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_19.geometry}
        material={nodes.mesh_0_19.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_20.geometry}
        material={nodes.mesh_0_20.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_21.geometry}
        material={nodes.mesh_0_21.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_22.geometry}
        material={nodes.mesh_0_22.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_23.geometry}
        material={nodes.mesh_0_23.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_24.geometry}
        material={nodes.mesh_0_24.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_25.geometry}
        material={nodes.mesh_0_25.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_26.geometry}
        material={nodes.mesh_0_26.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_27.geometry}
        material={nodes.mesh_0_27.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_28.geometry}
        material={nodes.mesh_0_28.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_29.geometry}
        material={nodes.mesh_0_29.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_30.geometry}
        material={nodes.mesh_0_30.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_31.geometry}
        material={nodes.mesh_0_31.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_32.geometry}
        material={nodes.mesh_0_32.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_33.geometry}
        material={nodes.mesh_0_33.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_34.geometry}
        material={nodes.mesh_0_34.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_35.geometry}
        material={nodes.mesh_0_35.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_36.geometry}
        material={nodes.mesh_0_36.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_37.geometry}
        material={nodes.mesh_0_37.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_38.geometry}
        material={nodes.mesh_0_38.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_39.geometry}
        material={nodes.mesh_0_39.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_40.geometry}
        material={nodes.mesh_0_40.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_41.geometry}
        material={nodes.mesh_0_41.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_42.geometry}
        material={nodes.mesh_0_42.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_43.geometry}
        material={nodes.mesh_0_43.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_44.geometry}
        material={nodes.mesh_0_44.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_45.geometry}
        material={nodes.mesh_0_45.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_46.geometry}
        material={nodes.mesh_0_46.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_47.geometry}
        material={nodes.mesh_0_47.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_48.geometry}
        material={nodes.mesh_0_48.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_49.geometry}
        material={nodes.mesh_0_49.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_50.geometry}
        material={nodes.mesh_0_50.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_51.geometry}
        material={nodes.mesh_0_51.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_52.geometry}
        material={nodes.mesh_0_52.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_53.geometry}
        material={nodes.mesh_0_53.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_54.geometry}
        material={nodes.mesh_0_54.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_55.geometry}
        material={nodes.mesh_0_55.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_56.geometry}
        material={nodes.mesh_0_56.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_57.geometry}
        material={nodes.mesh_0_57.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_58.geometry}
        material={nodes.mesh_0_58.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_59.geometry}
        material={nodes.mesh_0_59.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_60.geometry}
        material={nodes.mesh_0_60.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_61.geometry}
        material={nodes.mesh_0_61.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_62.geometry}
        material={nodes.mesh_0_62.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_63.geometry}
        material={nodes.mesh_0_63.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_64.geometry}
        material={nodes.mesh_0_64.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_65.geometry}
        material={nodes.mesh_0_65.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_66.geometry}
        material={nodes.mesh_0_66.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_67.geometry}
        material={nodes.mesh_0_67.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_68.geometry}
        material={nodes.mesh_0_68.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_69.geometry}
        material={nodes.mesh_0_69.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_70.geometry}
        material={nodes.mesh_0_70.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_71.geometry}
        material={nodes.mesh_0_71.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_72.geometry}
        material={nodes.mesh_0_72.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_73.geometry}
        material={nodes.mesh_0_73.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_74.geometry}
        material={nodes.mesh_0_74.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_75.geometry}
        material={nodes.mesh_0_75.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_76.geometry}
        material={nodes.mesh_0_76.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_77.geometry}
        material={nodes.mesh_0_77.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_78.geometry}
        material={nodes.mesh_0_78.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_79.geometry}
        material={nodes.mesh_0_79.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_80.geometry}
        material={nodes.mesh_0_80.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_81.geometry}
        material={nodes.mesh_0_81.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_82.geometry}
        material={nodes.mesh_0_82.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_83.geometry}
        material={nodes.mesh_0_83.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_84.geometry}
        material={nodes.mesh_0_84.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_85.geometry}
        material={nodes.mesh_0_85.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_86.geometry}
        material={nodes.mesh_0_86.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_87.geometry}
        material={nodes.mesh_0_87.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_88.geometry}
        material={nodes.mesh_0_88.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_89.geometry}
        material={nodes.mesh_0_89.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_90.geometry}
        material={nodes.mesh_0_90.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_91.geometry}
        material={nodes.mesh_0_91.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_92.geometry}
        material={nodes.mesh_0_92.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_93.geometry}
        material={nodes.mesh_0_93.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_94.geometry}
        material={nodes.mesh_0_94.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_95.geometry}
        material={nodes.mesh_0_95.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_96.geometry}
        material={nodes.mesh_0_96.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_97.geometry}
        material={nodes.mesh_0_97.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_98.geometry}
        material={nodes.mesh_0_98.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_99.geometry}
        material={nodes.mesh_0_99.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_100.geometry}
        material={nodes.mesh_0_100.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_101.geometry}
        material={nodes.mesh_0_101.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_102.geometry}
        material={nodes.mesh_0_102.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_103.geometry}
        material={nodes.mesh_0_103.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_104.geometry}
        material={nodes.mesh_0_104.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_105.geometry}
        material={nodes.mesh_0_105.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_106.geometry}
        material={nodes.mesh_0_106.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_107.geometry}
        material={nodes.mesh_0_107.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_108.geometry}
        material={nodes.mesh_0_108.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_109.geometry}
        material={nodes.mesh_0_109.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_110.geometry}
        material={nodes.mesh_0_110.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_111.geometry}
        material={nodes.mesh_0_111.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_112.geometry}
        material={nodes.mesh_0_112.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_113.geometry}
        material={nodes.mesh_0_113.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_114.geometry}
        material={nodes.mesh_0_114.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_115.geometry}
        material={nodes.mesh_0_115.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_116.geometry}
        material={nodes.mesh_0_116.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_117.geometry}
        material={nodes.mesh_0_117.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_118.geometry}
        material={nodes.mesh_0_118.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_119.geometry}
        material={nodes.mesh_0_119.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_120.geometry}
        material={nodes.mesh_0_120.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_121.geometry}
        material={nodes.mesh_0_121.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_122.geometry}
        material={nodes.mesh_0_122.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_123.geometry}
        material={nodes.mesh_0_123.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_124.geometry}
        material={nodes.mesh_0_124.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_125.geometry}
        material={nodes.mesh_0_125.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_126.geometry}
        material={nodes.mesh_0_126.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_127.geometry}
        material={nodes.mesh_0_127.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_128.geometry}
        material={nodes.mesh_0_128.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_129.geometry}
        material={nodes.mesh_0_129.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_130.geometry}
        material={nodes.mesh_0_130.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_131.geometry}
        material={nodes.mesh_0_131.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_132.geometry}
        material={nodes.mesh_0_132.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_133.geometry}
        material={nodes.mesh_0_133.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_134.geometry}
        material={nodes.mesh_0_134.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_135.geometry}
        material={nodes.mesh_0_135.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_136.geometry}
        material={nodes.mesh_0_136.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_137.geometry}
        material={nodes.mesh_0_137.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_138.geometry}
        material={nodes.mesh_0_138.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_139.geometry}
        material={nodes.mesh_0_139.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_140.geometry}
        material={nodes.mesh_0_140.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_141.geometry}
        material={nodes.mesh_0_141.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_142.geometry}
        material={nodes.mesh_0_142.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_143.geometry}
        material={nodes.mesh_0_143.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_144.geometry}
        material={nodes.mesh_0_144.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_145.geometry}
        material={nodes.mesh_0_145.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_146.geometry}
        material={nodes.mesh_0_146.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_147.geometry}
        material={nodes.mesh_0_147.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_148.geometry}
        material={nodes.mesh_0_148.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_149.geometry}
        material={nodes.mesh_0_149.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_150.geometry}
        material={nodes.mesh_0_150.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_151.geometry}
        material={nodes.mesh_0_151.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_152.geometry}
        material={nodes.mesh_0_152.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_153.geometry}
        material={nodes.mesh_0_153.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_154.geometry}
        material={nodes.mesh_0_154.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_155.geometry}
        material={nodes.mesh_0_155.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_156.geometry}
        material={nodes.mesh_0_156.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_157.geometry}
        material={nodes.mesh_0_157.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_158.geometry}
        material={nodes.mesh_0_158.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_159.geometry}
        material={nodes.mesh_0_159.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_160.geometry}
        material={nodes.mesh_0_160.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_161.geometry}
        material={nodes.mesh_0_161.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_162.geometry}
        material={nodes.mesh_0_162.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_163.geometry}
        material={nodes.mesh_0_163.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_164.geometry}
        material={nodes.mesh_0_164.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_165.geometry}
        material={nodes.mesh_0_165.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_166.geometry}
        material={nodes.mesh_0_166.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_167.geometry}
        material={nodes.mesh_0_167.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_168.geometry}
        material={nodes.mesh_0_168.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_169.geometry}
        material={nodes.mesh_0_169.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_170.geometry}
        material={nodes.mesh_0_170.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_171.geometry}
        material={nodes.mesh_0_171.material}
      >
        {/* <RockMaterial /> */}
      </mesh>
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_172.geometry}
        material={nodes.mesh_0_172.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_173.geometry}
        material={nodes.mesh_0_173.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_174.geometry}
        material={nodes.mesh_0_174.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_175.geometry}
        material={nodes.mesh_0_175.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_176.geometry}
        material={nodes.mesh_0_176.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_177.geometry}
        material={nodes.mesh_0_177.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_178.geometry}
        material={nodes.mesh_0_178.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_179.geometry}
        material={nodes.mesh_0_179.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_180.geometry}
        material={nodes.mesh_0_180.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_181.geometry}
        material={nodes.mesh_0_181.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_182.geometry}
        material={nodes.mesh_0_182.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_183.geometry}
        material={nodes.mesh_0_183.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_184.geometry}
        material={nodes.mesh_0_184.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_185.geometry}
        material={nodes.mesh_0_185.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_186.geometry}
        material={nodes.mesh_0_186.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_187.geometry}
        material={nodes.mesh_0_187.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_188.geometry}
        material={nodes.mesh_0_188.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_189.geometry}
        material={nodes.mesh_0_189.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_190.geometry}
        material={nodes.mesh_0_190.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_191.geometry}
        material={nodes.mesh_0_191.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_192.geometry}
        material={nodes.mesh_0_192.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_193.geometry}
        material={nodes.mesh_0_193.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_194.geometry}
        material={nodes.mesh_0_194.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_195.geometry}
        material={nodes.mesh_0_195.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_196.geometry}
        material={nodes.mesh_0_196.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_197.geometry}
        material={nodes.mesh_0_197.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_198.geometry}
        material={nodes.mesh_0_198.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_199.geometry}
        material={nodes.mesh_0_199.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_200.geometry}
        material={nodes.mesh_0_200.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_201.geometry}
        material={nodes.mesh_0_201.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_202.geometry}
        material={nodes.mesh_0_202.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_203.geometry}
        material={nodes.mesh_0_203.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_204.geometry}
        material={nodes.mesh_0_204.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_205.geometry}
        material={nodes.mesh_0_205.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_206.geometry}
        material={nodes.mesh_0_206.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_207.geometry}
        material={nodes.mesh_0_207.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_208.geometry}
        material={nodes.mesh_0_208.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_209.geometry}
        material={nodes.mesh_0_209.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_210.geometry}
        material={nodes.mesh_0_210.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_211.geometry}
        material={nodes.mesh_0_211.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_212.geometry}
        material={nodes.mesh_0_212.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_213.geometry}
        material={nodes.mesh_0_213.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_214.geometry}
        material={nodes.mesh_0_214.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_215.geometry}
        material={nodes.mesh_0_215.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_216.geometry}
        material={nodes.mesh_0_216.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_217.geometry}
        material={nodes.mesh_0_217.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_218.geometry}
        material={nodes.mesh_0_218.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_219.geometry}
        material={nodes.mesh_0_219.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_220.geometry}
        material={nodes.mesh_0_220.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_221.geometry}
        material={nodes.mesh_0_221.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_222.geometry}
        material={nodes.mesh_0_222.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_223.geometry}
        material={nodes.mesh_0_223.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_224.geometry}
        material={nodes.mesh_0_224.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_225.geometry}
        material={nodes.mesh_0_225.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_226.geometry}
        material={nodes.mesh_0_226.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_227.geometry}
        material={nodes.mesh_0_227.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_228.geometry}
        material={nodes.mesh_0_228.material}
      />
      <mesh
        castShadow={shouldCastShadow}
        receiveShadow={shouldReceiveShadow}
        geometry={nodes.mesh_0_229.geometry}
        material={nodes.mesh_0_229.material}
      />
      <group position={[-394.61, 158.44, 215.81]} scale={[0.78, 0.9, 0.85]}>
        <group position={[685.99, 0, 0]} scale={[-0.69, 0.68, 0.69]}>
          <group position={[0, 846.46, 0]} scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_14.geometry}
              material={nodes.mesh_14.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_14_1.geometry}
              material={nodes.mesh_14_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_3.geometry}
              material={nodes.group_2_3.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_3.geometry}
              material={nodes.group_3_3.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_3.geometry}
              material={nodes.group_4_3.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
          <group position={[0, 551.18, 0]} scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_18.geometry}
              material={nodes.mesh_18.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_18_1.geometry}
              material={nodes.mesh_18_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_4.geometry}
              material={nodes.group_2_4.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_4.geometry}
              material={nodes.group_3_4.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_4.geometry}
              material={nodes.group_4_4.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
          <group position={[0, 295.67, 0]} scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_22.geometry}
              material={nodes.mesh_22.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_22_1.geometry}
              material={nodes.mesh_22_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_5.geometry}
              material={nodes.group_2_5.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_5.geometry}
              material={nodes.group_3_5.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_5.geometry}
              material={nodes.group_4_5.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
          <group scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_26.geometry}
              material={nodes.mesh_26.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_26_1.geometry}
              material={nodes.mesh_26_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_6.geometry}
              material={nodes.group_2_6.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_6.geometry}
              material={nodes.group_3_6.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_6.geometry}
              material={nodes.group_4_6.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
        </group>
        <group position={[338.52, 0, 0]} scale={[0.69, 0.68, 0.69]}>
          <group position={[0, 846.46, 0]} scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_39.geometry}
              material={nodes.mesh_39.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_39_1.geometry}
              material={nodes.mesh_39_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_10.geometry}
              material={nodes.group_2_10.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_10.geometry}
              material={nodes.group_3_10.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_10.geometry}
              material={nodes.group_4_10.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
          <group position={[0, 551.18, 0]} scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_43.geometry}
              material={nodes.mesh_43.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_43_1.geometry}
              material={nodes.mesh_43_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_11.geometry}
              material={nodes.group_2_11.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_11.geometry}
              material={nodes.group_3_11.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_11.geometry}
              material={nodes.group_4_11.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
          <group position={[0, 295.67, 0]} scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_47.geometry}
              material={nodes.mesh_47.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_47_1.geometry}
              material={nodes.mesh_47_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_12.geometry}
              material={nodes.group_2_12.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_12.geometry}
              material={nodes.group_3_12.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_12.geometry}
              material={nodes.group_4_12.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
          <group scale={2.32}>
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_51.geometry}
              material={nodes.mesh_51.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.mesh_51_1.geometry}
              material={nodes.mesh_51_1.material}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_2_13.geometry}
              material={nodes.group_2_13.material}
              position={[5.87, 11.75, 53.5]}
              rotation={[Math.PI, 0, 0]}
              scale={1.02}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_3_13.geometry}
              material={nodes.group_3_13.material}
              position={[17.4, 17.4, 0]}
              rotation={[0, 0, Math.PI]}
              scale={3.16}
            />
            <mesh
              castShadow={shouldCastShadow}
              receiveShadow={shouldReceiveShadow}
              geometry={nodes.group_4_13.geometry}
              material={nodes.group_4_13.material}
              position={[7.62, 8.55, 0.97]}
              scale={[1, 1, 1.44]}
            />
          </group>
        </group>
        <group position={[0, 201.31, 0]} scale={[1.6, 1.58, 1.6]}>
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_30.geometry}
            material={nodes.mesh_30.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_30_1.geometry}
            material={nodes.mesh_30_1.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_2_7.geometry}
            material={nodes.group_2_7.material}
            position={[5.87, 11.75, 53.5]}
            rotation={[Math.PI, 0, 0]}
            scale={1.02}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_3_7.geometry}
            material={nodes.group_3_7.material}
            position={[17.4, 17.4, 0]}
            rotation={[0, 0, Math.PI]}
            scale={3.16}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_4_7.geometry}
            material={nodes.group_4_7.material}
            position={[7.62, 8.55, 0.97]}
            scale={[1, 1, 1.44]}
          >
            <group position={[6.75, 40.03, -8.12]} scale={[0.67, 1.21, 1.05]}>
              <group position={[-10.18, -31.37, 7.72]} rotation={[0, 0, -0.51]}>
                <mesh
                  castShadow={shouldCastShadow}
                  receiveShadow={shouldReceiveShadow}
                  geometry={nodes.Component_6_1.geometry}
                  material={nodes.Component_6_1.material}
                />
              </group>
            </group>
          </mesh>
        </group>
        <group position={[0, 385.51, 0]} scale={[1.6, 1.58, 1.6]}>
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_35.geometry}
            material={nodes.mesh_35.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_35_1.geometry}
            material={nodes.mesh_35_1.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_2_8.geometry}
            material={nodes.group_2_8.material}
            position={[5.87, 11.75, 53.5]}
            rotation={[Math.PI, 0, 0]}
            scale={1.02}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_3_8.geometry}
            material={nodes.group_3_8.material}
            position={[17.4, 17.4, 0]}
            rotation={[0, 0, Math.PI]}
            scale={3.16}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_4_8.geometry}
            material={nodes.group_4_8.material}
            position={[7.62, 8.55, 0.97]}
            scale={[1, 1, 1.44]}
          />
        </group>
        <group position={[0, 576.31, 0]} scale={[1.6, 1.58, 1.6]}>
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_55.geometry}
            material={nodes.mesh_55.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_55_1.geometry}
            material={nodes.mesh_55_1.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_2_9.geometry}
            material={nodes.group_2_9.material}
            position={[5.87, 11.75, 53.5]}
            rotation={[Math.PI, 0, 0]}
            scale={1.02}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_3_9.geometry}
            material={nodes.group_3_9.material}
            position={[17.4, 17.4, 0]}
            rotation={[0, 0, Math.PI]}
            scale={3.16}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_4_9.geometry}
            material={nodes.group_4_9.material}
            position={[7.62, 8.55, 0.97]}
            scale={[1, 1, 1.44]}
          />
        </group>
        <group position={[1024.51, 576.31, 0]} scale={[-1.6, 1.58, 1.6]}>
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_1.geometry}
            material={nodes.mesh_1.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_1_1.geometry}
            material={nodes.mesh_1_1.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_2.geometry}
            material={nodes.group_2.material}
            position={[5.87, 11.75, 53.5]}
            rotation={[Math.PI, 0, 0]}
            scale={1.02}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_3.geometry}
            material={nodes.group_3.material}
            position={[17.4, 17.4, 0]}
            rotation={[0, 0, Math.PI]}
            scale={3.16}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_4.geometry}
            material={nodes.group_4.material}
            position={[7.62, 8.55, 0.97]}
            scale={[1, 1, 1.44]}
          >
            <group position={[6.75, 40.03, -8.12]} scale={[0.67, 1.21, 1.05]}>
              <group position={[-10.18, -31.37, 7.72]} rotation={[0, 0, -0.51]}>
                <mesh
                  castShadow={shouldCastShadow}
                  receiveShadow={shouldReceiveShadow}
                  geometry={nodes.Component_6.geometry}
                  material={nodes.Component_6.material}
                />
              </group>
            </group>
          </mesh>
        </group>
        <group position={[1024.51, 375.27, 0]} scale={[-1.6, 1.58, 1.6]}>
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_6.geometry}
            material={nodes.mesh_6.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_6_1.geometry}
            material={nodes.mesh_6_1.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_2_1.geometry}
            material={nodes.group_2_1.material}
            position={[5.87, 11.75, 53.5]}
            rotation={[Math.PI, 0, 0]}
            scale={1.02}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_3_1.geometry}
            material={nodes.group_3_1.material}
            position={[17.4, 17.4, 0]}
            rotation={[0, 0, Math.PI]}
            scale={3.16}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_4_1.geometry}
            material={nodes.group_4_1.material}
            position={[7.62, 8.55, 0.97]}
            scale={[1, 1, 1.44]}
          />
        </group>
        <group position={[1024.51, 201.31, 0]} scale={[-1.6, 1.58, 1.6]}>
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_10.geometry}
            material={nodes.mesh_10.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.mesh_10_1.geometry}
            material={nodes.mesh_10_1.material}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_2_2.geometry}
            material={nodes.group_2_2.material}
            position={[5.87, 11.75, 53.5]}
            rotation={[Math.PI, 0, 0]}
            scale={1.02}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_3_2.geometry}
            material={nodes.group_3_2.material}
            position={[17.4, 17.4, 0]}
            rotation={[0, 0, Math.PI]}
            scale={3.16}
          />
          <mesh
            castShadow={shouldCastShadow}
            receiveShadow={shouldReceiveShadow}
            geometry={nodes.group_4_2.geometry}
            material={nodes.group_4_2.material}
            position={[7.62, 8.55, 0.97]}
            scale={[1, 1, 1.44]}
          />
        </group>
      </group>
    </group>
  );
}
